for i=1:5
    aux = A70BS100_I_th8_pf(i);
    neg_values = get(aux, 'intensities') < 0;
    aux = delete(aux, neg_values);
    high_values = get(aux, 'intensities') >= 10000;
    aux = delete(aux, high_values);
    A70BS100_I_th8_pfc(i) = aux;
end
i = 1;
aux = A70BS100_I_th8_pf(i);
neg_values = get(aux, 'intensities') < 0;
aux = delete(aux, neg_values);
high_values = get(aux, 'intensities') >= 600;
aux = delete(aux, high_values);
A70BS100_I_th8_pfc(i) = aux;
i = 2;
aux = A70BS100_I_th8_pf(i);
neg_values = get(aux, 'intensities') < 0;
aux = delete(aux, neg_values);
high_values = get(aux, 'intensities') >= 200;
aux = delete(aux, high_values);
A70BS100_I_th8_pfc(i) = aux;
i = 3;
aux = A70BS100_I_th8_pf(i);
neg_values = get(aux, 'intensities') < 0;
aux = delete(aux, neg_values);
high_values = get(aux, 'intensities') >= 100;
aux = delete(aux, high_values);
A70BS100_I_th8_pfc(i) = aux;
i = 4;
aux = A70BS100_I_th8_pf(i);
neg_values = get(aux, 'intensities') < 0;
aux = delete(aux, neg_values);
high_values = get(aux, 'intensities') >= 150;
aux = delete(aux, high_values);
A70BS100_I_th8_pfc(i) = aux;
i = 5;
aux = A70BS100_I_th8_pf(i);
neg_values = get(aux, 'intensities') < 0;
aux = delete(aux, neg_values);
high_values = get(aux, 'intensities') >= 60;
aux = delete(aux, high_values);
A70BS100_I_th8_pfc(i) = aux;