%% Import Script for PoleFigure Data
%
% This script was automatically created by the import wizard. You should
% run the whoole script or parts of it in order to import your data. There
% is no problem in making any changes to this script.

%% Specify Crystal and Specimen Symmetries

% crystal symmetry
CS = symmetry('cubic');

% specimen symmetry
SS = symmetry('triclinic');

% plotting convention
setMTEXpref('xAxisDirection','east');
setMTEXpref('zAxisDirection','outOfPlane');

%% Specify File Names

% path to files
pname = '/home/benattie/Documents/Doctorado/Git/tmp/Al70R/out/cut_pole_figures/raw';

% which files to be imported
fname = {...
  [pname '/H_New_Al70R-tex_ALL_PF_1.mtex'],...
  [pname '/H_New_Al70R-tex_ALL_PF_2.mtex'],...
  [pname '/H_New_Al70R-tex_ALL_PF_3.mtex'],...
  [pname '/H_New_Al70R-tex_ALL_PF_4.mtex'],...
  [pname '/H_New_Al70R-tex_ALL_PF_5.mtex'],...
  [pname '/H_New_Al70R-tex_ALL_PF_6.mtex'],...
  [pname '/H_New_Al70R-tex_ALL_PF_7.mtex'],...
  };

%% Specify Miller Indice

h = { ...
  Miller(1,1,1,CS),...
  Miller(2,0,0,CS),...
  Miller(2,2,0,CS),...
  Miller(3,1,1,CS),...
  Miller(2,2,2,CS),...
  Miller(4,0,0,CS),...
  Miller(3,3,1,CS),...
  };

%% Import the Data

% create a Pole Figure variable containing the data
Al70R_H_th8_pf = loadPoleFigure(fname,h,CS,SS,'interface','generic',...
  'ColumnNames', { 'Polar Angle' 'Azimuth Angle' 'Intensity'}, 'Columns', [4 5 6], 'wizard', 'wizard', 'wizard', 'wizard', 'wizard', 'wizard', 'wizard');

