for i=1:7
    aux = Al70R_H_th8_pf(i);
    neg_values = get(aux, 'intensities') < 0;
    aux = delete(aux, neg_values);
    high_values = get(aux, 'intensities') >= 500;
    aux = delete(aux, high_values);
    Al70R_H_th8_pfc(i) = aux;
end
i = 1;
aux = Al70R_H_th8_pf(i);
neg_values = get(aux, 'intensities') <= 0.020;
aux = delete(aux, neg_values);
high_values = get(aux, 'intensities') >= 0.024;
aux = delete(aux, high_values);
Al70R_H_th8_pfc(i) = aux;
i = 2;
aux = Al70R_H_th8_pf(i);
neg_values = get(aux, 'intensities') <= 0;
aux = delete(aux, neg_values);
high_values = get(aux, 'intensities') >= 0.030;
aux = delete(aux, high_values);
Al70R_H_th8_pfc(i) = aux;
i = 3;
aux = Al70R_H_th8_pf(i);
neg_values = get(aux, 'intensities') <= 0;
aux = delete(aux, neg_values);
high_values = get(aux, 'intensities') >= 0.028;
aux = delete(aux, high_values);
Al70R_H_th8_pfc(i) = aux;
i = 4;
aux = Al70R_H_th8_pf(i);
neg_values = get(aux, 'intensities') <= 0;
aux = delete(aux, neg_values);
high_values = get(aux, 'intensities') >= 0.031;
aux = delete(aux, high_values);
Al70R_H_th8_pfc(i) = aux;
% i = 5;
% aux = Al70R_H_th8_pf(i);
% neg_values = get(aux, 'intensities') <= 0;
% aux = delete(aux, neg_values);
% high_values = get(aux, 'intensities') >= 50;
% aux = delete(aux, high_values);
% Al70R_H_th8_pfc(i) = aux;